# Step 0 - Build the docker image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'asia-east1-docker.pkg.dev/project-pic-cloudap/wilson-gcp-cicd/testwebserver:v1', '.' ]

# Step 1 - Run unit tests inside the docker container
- name: 'asia-east1-docker.pkg.dev/project-pic-cloudap/wilson-gcp-cicd/testwebserver:v1'
  entrypoint: python
  args: ["-m", "pytest", "."] 

# Step 2 - Push the docker image to be used by Cloud Run
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-east1-docker.pkg.dev/project-pic-cloudap/wilson-gcp-cicd/testwebserver:v1']

# Step 3 - Deploy the image in a cloud run container
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'cloudrunservice'
  - '--image'
  - 'asia-east1-docker.pkg.dev/project-pic-cloudap/wilson-gcp-cicd/testwebserver:v1'
  - '--region'
  - 'asia-east1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--port'
  - '3000'